# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('school', models.CharField(max_length=255)),
                ('std', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
